### ISSUE TITLE
Site structure/initialization.

### ISSUE THREAD

**Issue by ghost** [NashvilleSoftwareSchool/Cohort7Website#1]
What should we be using and does everyone feel comfortable with for the site? Jekyii is fine. the downside is that we don't really need all of it ( I don't see us needing to make blog posts from this site) Upside being that we can use collections to loop over each of us which would make everything more convenient. Also we could just host it from the `gh-pages` branch, so even less to worry about. 

We could just use a static site (index.html, style.css, app.js) if anyone had a good reason for it, but the collection of students thing would be a hassle like i said above. 

Also if anyone else has any suggestions that I've overlooked feel free to talk about it here. 

My vote is for jekyll and finishing this decision this as soon as possible so we can actually get to work on it. Whaddya think friends?

**Comment by gwake1** [comment]
Hey Colby,

Good suggestion.  I am down for Jekyll.

Any preferences for UI libraries or frameworks?

Gerald

**Comment by BlaiseGratton** [comment]
Yeah, Jekyll sans blog would be good I think.

**Comment by beck410** [comment]
Jekyll 
I like working with neat and bourbon for frameworks/grid but there's also jekyll-foundation for a quick UI

**Comment by evanroane** [comment]
The jekyll-foundation project has an issue with mobile menu that is
probably fixable. I'm going to sort that out on my own site and we can use
the solution once I sort that out.

Also--we should think about using this for a splash:
http://adamschwartz.co/letters/

**Comment by beck410** [comment]
I could take the mobile menu part out of foundation and put in the custom code i use for all my site's mobile menus - it's not too much of an issue

**Comment by SondaSengupta** [comment]
So we have a few options here, and I agree with Colby that we should just make this ASAP. Our personal sites are much more important anyways. Eliza suggested that we just download a Jekyll theme that is similar and modify that for our styling (MIT ones of course)
Here's a neat one with a splashy page: http://jekyllthemes.org/themes/hmfaysal-omega-theme/

Next option is fork 6's repo and then overhaul it.

Last and the longest option would be to completely redesign our own. My leaning is to just use a jekyll theme, and then code from there. If there is an MIT theme you like, please post.

**Comment by gwake1** [comment]
I like Sonda's suggested theme and I think Beck's suggestion on the Jekyll Foundation UI Framework will be easiest to implement.  
- [ ] Download Sonda's <a href="http://jekyllthemes.org/themes/hmfaysal-omega-theme/" target="_blank">Jekyll theme</a>
- [ ] <a href="http://developmentsindigital.com/jekyll/blog/2014/04/09/adding-foundation-to-a-jekyll-blog.html" target="_blank"> Integrate Foundation with Jekyll Blog </a>and Sonda's Theme

**Comment by SondaSengupta** [comment]
It's been great having a huge amount of support for the project, but only a few are needed to get it done. Here's what I'm thinking.
-I will download and install the the jekyll theme on a branch.
- @colbydehart, I was hoping you would come after and add the code you had created with the alumni site and repurpose it for our bio photos.
- @JaclynPasquale as our class designer, it would be great to modify the base theme for a layout which would include not only our bios, but a place for a group photo and a place for blurb about the tech stuff we know. You can either wait until we're finished to get started or start hashing some ideas on a separate branch with example html and css if you prefer.
- @beck410 I think mobile is already supported via the theme, but in case it does not, it will be great to have your help getting a mobile version working later on when we have layout and bios sorted out.

Colby, Jackie, Beck -- please let me know if all this sounds doable. If there are no objections about this plan, I will start working on this tomorrow.

If any others have an idea, you are welcome to put them to work on another branch, tag me on an issue, and submit a pull request when your ready. As always, do not push to master.

**Comment by BlaiseGratton** [comment]
Unless you're Beck, in which case say 'master' as you will, or your name rhymes with madame lay fur.

**Comment by SondaSengupta** [comment]
ah yes, please don't push to mastah :)

**Comment by beck410** [comment]
:+1:  glad for the translation there guys!
