### ISSUE TITLE
Post your bios everyone!

### ISSUE THREAD

**Issue by SondaSengupta** [NashvilleSoftwareSchool/Cohort7Website#13]
Here! Here! Post your bios, please! To make life easier, just post your content right here in this thread, and I'll just make everyone's markdown files in one fell swoop before next Wed, the 18th. No pull requests, no hassles. Thanks to Brandon and Kimberly who've done it already. Here is Kimberly's below as a template example:

name: Kimberly Lewis
## site: http://www.thatknitter.com

I go by thestashattacked on Ravelry and thatknitter everywhere else. I'm a web developer and knitter who enjoys designing her own patterns, cat videos, and boxing.

**Comment by SondaSengupta** [comment]
oh and don't worry about how it looks on this thread since it may look a bit wonky here. It'll be fine, as long it's this:
name: Your Name
site: Your Personal Ste
1-2 sentences about yourself. 

Thanks, everyone.

**Comment by ghost** [comment]
Just follow the _template.md file's layout.
