### ISSUE TITLE
Deployment and Class Website URL

### ISSUE THREAD

**Issue by SondaSengupta** [NashvilleSoftwareSchool/Cohort7Website#15]
@elizabrock, can you give us the link to our nss cohort site so that the whole class can see the site? I'd hate for them to have to git clone it, just to view it.

**Comment by elizamarcum** [comment]
You have to push to the gh-pages branch before github will make the site publicly viewable. 

-Eliza

elizabrocksoftware.com

twitter.com/elizabrock

(858) 205-9285

**Comment by SondaSengupta** [comment]
I made the gh-pages branch and it is currently has all the content of master

**Comment by elizamarcum** [comment]
@SondaSengupta It is up at http://nashvillesoftwareschool.github.io/Cohort7Website/, but it looks like a lot of the assets were hardcoded as absolute rather than relative URLs, so they aren't showing up well at that URL.

**Comment by johnwark** [comment]
Well, looks like there's a bit of clean-up work to do on the site - but you
guys take a GREAT class picture.

john

On Thu, Mar 19, 2015 at 1:29 PM, Eliza Brock notifications@github.com
wrote:

> @SondaSengupta https://github.com/SondaSengupta It is up at
> http://nashvillesoftwareschool.github.io/Cohort7Website/, but it looks
> like a lot of the assets were hardcoded as absolute rather than relative
> URLs, so they aren't showing up well at that URL.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/NashvilleSoftwareSchool/Cohort7Website/issues/15#issuecomment-83704049
> .

## 

John Wark
Nashville Software School http://www.nashvillesoftwareschool.com
m | 615.306.0885

**Comment by SondaSengupta** [comment]
So, I know that we are trying to get it to show on nss.elizabrocksoftware.com for the time being, but it's been more than a day and the site is still not showing up.

**Comment by elizamarcum** [comment]
@SondaSengupta The `CNAME` file has to be on the gh-pages branch.

**Comment by SondaSengupta** [comment]
Done.

**Comment by SondaSengupta** [comment]
@JaclynPasquale Everything is merged in and it looks great.

**Comment by evanroane** [comment]
http://cohort7.nashvillesoftwareschool.com/ is looking good :)
