### ISSUE TITLE
Content of this Website Page

### ISSUE THREAD

**Issue by SondaSengupta** [NashvilleSoftwareSchool/Cohort7Website#2]
We should think about content. I would say:
-Group Photo with perhaps a small blurb about who we are and what we specialize as a class
-Then individual photos of people with captions (How?, like carousal, an instagrammy page...)
-Perhaps pictures of technologies we covered in class

**Comment by gwake1** [comment]
<a href="https://nss-cohort-2014-06-07.github.io/" target="_blank">NSS Cohort 6 Website</a>

I agree.  I think we could sample some of the code Colby implemented in the NSS website utilizing a separate collection containing info on each student linking to a separate page dedicated to the student with a little more personal information.

**Comment by gwake1** [comment]
Also I am not a fan of displaying the funny photos on the main page.  I think the main page should be kept to professional/business and display a different side of our personalities on a separate individual student page via carousel.

**Comment by beck410** [comment]
Just throwing it out there but do we really need separate pages - isn't that what our portfolio sites are for?

**Comment by SondaSengupta** [comment]
No, don't need it all, but Colby may need the extra pages as a collection
for the bio blurbs. This site will be a ghpage of nss site i think.

**Comment by beck410** [comment]
he won't need extra pages that lead somewhere - just files for the collection unless we want to put the bio on a separate page due to spacing issues - i'm all for that

**Comment by ghost** [comment]
I say :-1: on making individual pages in the cohort site for each student. 

We can have a collection of students that drops down with a short bio and a link to our portfolio sites, just like in the NSS website. 

A single page for each student would be pretty bare/waste of a click of navigation, plus I see nightmares with people wanting to customize their pages with different content/different styling/javascript game of snake.

**Comment by SondaSengupta** [comment]
All right, I agree. And since no one's liked that idea, we'll just go for a
single page site with the bio drop down that Colby said.

So right now, we have:
-Group Photo
-Short class intro about who we are and our class technologies
-bio boxes

I like the idea that if you hover over the group photo, you see the funny
photo.

**Comment by gwake1** [comment]
Hey Guys,

Final defense on individual web pages on the group site.

Since this will most likely be the source for where future mentors and
employers will go to see the list of students at NSS I would prefer that
their choice in deciding on a student isn't based on a small image and a
tag line.

I think it would be beneficial for everyone to have a single page provided
with a short bio of each student to help future employers and mentors
decide on which students they want to further invest time into researching.
I think this is better as opposed to having to invest time in viewing every
individual's website to get a feel for the student, which is highly
unlikely.

Our individual websites should contain a wealth of data that won't be
discounted by having a dedicated page on the cohort site.

Gerald

**Comment by SondaSengupta** [comment]
Well the bio blurb can be as long or as short as you like it, if I'm not mistaken since it's a dropdown to a dialog box when you click on a person's image. Personally I think another page will be just as tedious for a mentor to go to as going to another site altogether because it a hyperlink either way.

**Comment by ghost** [comment]
> Personally I think another page will be just as tedious for a mentor to go to as going to another site altogether because it a hyperlink either way.

This. You can always just make your link go to the about page of your own site, which is in my mind the same as an about page on this site, except waaaaaay less of a hassle, because of having to decide on what everyone's personal page would look like..

**Comment by evanroane** [comment]
My preference is for the links to go to our individual sites. Less content
creation...and its a great incentive to get one's site into a polished
state.

**Comment by beck410** [comment]
i vote for links going to individual sites - theres enough information out there on us between our personal sites/linkedin/github
