### ISSUE TITLE
Photo Votes

### ISSUE THREAD

**Issue by SondaSengupta** [NashvilleSoftwareSchool/Cohort7Website#7]
Post your votes. I personally think BW on the site for serious, and then colored fun photo. But vote on what you like. This issue needs to be answered quickly as per John and Inge's request. Thanks!

**Comment by jspencersharpe** [comment]
I agree, Sonda.

**Comment by luketucker28** [comment]
Im good with it as well.

**Comment by brandontate** [comment]
+1 Grape Mastah

**Comment by AlexStory** [comment]
:+1:

**Comment by LeonM234** [comment]
Works for me. 

```
 On Thursday, March 5, 2015 4:19 PM, AlexStory <notifications@github.com> wrote:
```

**Comment by ghost** [comment]
:snail: :shower: 

(yes)

**Comment by JaclynPasquale** [comment]
Sounds good to me.

**Comment by beck410** [comment]
:+1:

**Comment by evanroane** [comment]
Agree

**Comment by stephania07** [comment]
sounds good

**Comment by SondaSengupta** [comment]
All right, sent John an email and he approved.
