### ISSUE TITLE
Student Bios

### ISSUE THREAD

**Issue by SondaSengupta** [NashvilleSoftwareSchool/Cohort7Website#8]
@colbydehart , top of the morning,

I added some content and made it so that the photos can switch out when you mouseover, since that was the voting stated. The navigation works too.

I added the content for the accordian bio drop-down thing in the main.js file, but when you click on your batman photo, it just wiggles a bit. Can you make it like the mentor blurbs from the nashvillesoftwareschool page? If not, we might have to just have largish profile squares w/o the animation. Let me know how it goes! Later on, I might ask the class what they want on their blurb (maybe their name, website, github, and two sentence intro?)... God's speed and :four_leaf_clover:

**Comment by ghost** [comment]
Excellent! Those sound fine, if anyone else thinks there should be something else, let it be heard now before we standardize a markdown template. Can anyone think of any more properties we should use besides site and github?

After we decide the info we need for everyone, I'll make a template that will basically look like

``` markdown
---
name: Colby DeHart
site: colbydehart.com
github: github.com/colbydehart
---
My name is colby and I'm here to say, that I came to rap in a real cool way.
```

After this template is made, everyone can just make their own markdown file and put it in the `_students/` folder. 

In my mind, the best way to do this that doesn't involve 20 pull requests is just going into github, making a new file in the _students folder and editing it with the built in github editor that allows instant committing to master branch. That way you are only committing one file that no one else should be touching and we don't have any inadvertent conflicts.

**Comment by SondaSengupta** [comment]
If anyone doesn't feel comfortable with instant committing like Colby's talking about, just send me your markdown text in an email. I'll make a file for you and commit it, no probs. :cake:
